from typing import Any
__version__: str
class PopulationFitDataset:
    request: dict[str, Any]
    subject_ids: tuple[str, ...]
    mapping: tuple[dict[str, Any], ...]
def population_fit_dataset(
    data: Any, template: str | dict[str, Any], *,
    compartments: dict[Any, str], endpoints: dict[Any, dict[str, Any]],
    time_unit: str, amount_unit: str, rate_unit: str | None = ...,
    observation_side: str = ...,
) -> PopulationFitDataset: ...
class PharmfluxError(ValueError):
    diagnostic: dict[str, Any]
    code: str
    time: float | None
    expression: str | None
    line: int | None
    column: int | None
class CompiledModel:
    def __init__(self, source: str | dict[str, Any]) -> None: ...
    @property
    def model_content_hash(self) -> str: ...
    @property
    def output_names(self) -> list[str]: ...
    @property
    def output_units(self) -> list[str]: ...
    def run(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def morris(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def morris_json(self, request: str | dict[str, Any]) -> str: ...
    def scan(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def scan_json(self, request: str | dict[str, Any]) -> str: ...
    def periodic_steady_state(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def iterate_periodic_state(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def run_json(self, request: str | dict[str, Any]) -> str: ...
    def fit_scalar(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def fit_scalar_json(self, request: str | dict[str, Any]) -> str: ...
def format_model(source: str | dict[str, Any]) -> str: ...

class CompiledSensitivities:
    def __init__(self, source: str | dict[str, Any], with_respect_to: list[str]) -> None: ...
    def run(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def run_json(self, request: str | dict[str, Any]) -> str: ...
    def fit(self, request: str | dict[str, Any]) -> dict[str, Any]: ...
    def fit_json(self, request: str | dict[str, Any]) -> str: ...
    def fit_population_data(self, dataset: PopulationFitDataset) -> dict[str, Any]: ...
